version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moysklad
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: moysklad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
